### ISSUE TITLE
Work flow in ICARO

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#108]
I am trying to document (and also to understand) the work flow for a "typical" developer working in ICARO (the analysis repository). Two important points are:

1) ICARO is a client of IC. This means that all relevant, general stuff (e.g, fitting_functions.py) developed while working in an specific analysis must be exported to IC (e.g, fitting_functions.py belongs to /core). 

2) Does that mean that all people working in ICARO has to go through the chores of forking IC, creating the corresponding branch, including fitting_functions.py, and making a PR? This scheme, is the simplest one, but it requires that every one working in analysis interacts with IC, which increases the numbers of developers working in IC, which may create complications (or not).

3) Is there an alternative? One could imagine creating a folder /export_to_IC folder in ICARO, so that the normal user of ICARO, on her pull request, includes /export_to_ic/core/fitting_functions.py. When the PR is approved (by the dictator(s) of ICARO), then the dictator(s) move fitting_functions.py to IC.  

4) I tend to prefer the second method, but I don't know if we hit here the usual situation best described in Spanish: "desnudar a un santo para vestir a otro". 
what do you think @jacg, @jmbenlloch ?

(let's agree on something, since I am writing documentation...)

**Comment by jacg** [comment]
> Does that mean that all people working in ICARO has to go through
> the chores of forking IC, creating the corresponding branch,
> including fitting_functions.py, and making a PR?

Yes, creating a PR would seemt to be the obvious way to go. My
impression is that these PRs would almost always add new content,
rather than changing old content, which means that there will be no
conflicts, which means that (with a decent porcelain) it's not that
much of a chore. Writing a decent commit message will be by far the
biggest part of the task, and this is something that I presume we 

> This scheme, is the simplest one, but it requires that every one
> working in analysis interacts with IC, which increases the numbers
> of developers working in IC,

Hmm, I'd call them contributors rather than developers. They don't
really need to know anything about IC other than where their
contributed files are expected to go.

> 1. Is there an alternative? One could imagine creating a folder
>    /export_to_IC folder in ICARO, so that the normal user of ICARO,
>    on her pull request, includes
>    /export_to_ic/core/fitting_functions.py. When the PR is approved
>    (by the dictator(s) of ICARO), then the dictator(s) move
>    fitting_functions.py to IC.

IIUC, the difference is that in the second scheme, the analyst has
forked one repo (ICARO), while in the first there are two forks (ICARO
and IC). In both cases the analyst has to make a PR, the only
difference being, to which repository?

> 1. I tend to prefer the second method, but I don't know if we hit
> here the usual situation best described in Spanish: "desnudar a un
> santo para vestir a otro".

... or in English: "Rob Peter to pay Paul".

> what do you think @jacg, @jmbenlloch ?

How frequently will this happen? How frequently will an analyst open
PRs to IC compared to the frequency with which the same analyst will
open PRs to ICARO. Let's use `R` to denote the ratio

    frequency of PRs to IC / frequency of PRs to ICARO

for a typical ICARO user. If `R` is a tiny fraction of 1, then the
second scheme might be worth it. If `R` approaches 1 (from below), the
second scheme becomes less and less useful. If `R` is significantly
greater than 1, then the second scheme is probably counterproductive.

My point is that if the analyist is used do opening PRs to ICARO, and
then, once in a blue moon, has to open a PR to IC, then it might be
worthwhile to avoid this exceptional circumstance and thus reduce
confusion, by using the second scheme. If sending stuff up to IC is
the norm, rather than being rare and exceptional, then let's just do
it the normal way.

If it *is* exceptional, the analysts may make a complete dog's
breakfast out of the process in 9 out of 10 cases, and require the
help or intervention of an IC developer. In this case, it might be
cheaper for the IC developers to take charge of all communication with
the IC repo.

**Comment by jjgomezcadenas** [comment]
Yes, I agree, it all depends on R.

My feeling is that most people in NEXT will be analysts. They will work in their own thing, and will eventually come up with useful functions of general interest. Only a few of us will work in both worlds. As the experiment progresses and more people joins, I think the situation will be more and more biased towards a majority of analysis people and a minority of reconstruction people.

So I would tend to think that in the medium term (and maybe in the short term too) it is worth to foresee the possibility than an analyst does not need to worry about IC (those who want to fork IC and work with it, of course are very welcomed to do so). But maybe the scenarios will become clearer after the workshop.

**Comment by jjgomezcadenas** [comment]
After many months of work it is clear that ICARO is just a client of IC, but we have no way to enhance IC standards there (too fast development and NB driven development). We will need to reckon with ICARO at some other time, if ever.
