### ISSUE TITLE
PMAP Writer

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#158]
After a quick discussion, we believe that there is a handy solution to separate the functionality of computing PMAPS from that of saving them to file. We propose to write a PMapWriter beast (aka class) that takes care of that core and can be called either by Irene or other clients. We propose to open a specific branch for this. @jmbenlloch has finger-volunteered to take this job.

**Comment by jacg** [comment]
> We propose to write a PMapWriter beast (aka class)

What advantages does a class offer over a function, in this case?

I may well be missing something, but I think that we need two functions:

+ one of them will be the inverse of the one which is currently called `xxx` in the branch called `dataframe-to-dict-s12` in my fork (which is essentially a rewrite of `s12df_to_s12l`);
+ the other will be similar, but slightly different to account for the difference between PMT and SiPM data.

So, altogether two pairs of functions: two transient -> persistent, along with their two inverses. And I don't see how classes help here.

@neuslopez was involved in the development of `xxx`, so may have something to say on this.

**Comment by neuslopez** [comment]
Your comment above @jacg, are just the perfect words for what I would say and I had in mind when we wrote xxx!!

Re-saying: we need two functions (transient <-> persisent) and we need to duplicate these two to account for the PMTs and SiPMs (as the dict that @jjgomezcadenas had in mind is different for those sensors)-----> 4 functions.

Our xxx corresponds to: persistent (dataFrame) -> transient (dict) for PMTs. 

Note: tomorrow I plan to timeit xxx and compare it with s12df_to_s12l

**Comment by jjgomezcadenas** [comment]
To summarise the discussion:

1. We all agree that we need a function/class to handle persistent <--> transient representation of PAMPS.

2. It appears that @jacg and @neuslopez have been playing around with some possibilities in branch xxx. My first reaction when I read "a rewrite of a function" (in particular if I wrote the function with some pain) is: why? Also, I believe that @gonzaponte has his own version of that particular function in a PR not yet approved. It is in my list (as requested by @jacg) to review @gonzaponte PR, which I will do next. Unless I have to I will not look at branch xxx.

3. Concerning the use of a function or a class, it is clearly a matter of taste. Perhaps the first question to ask is who is going to implement the classes/functions.  @jmbenlloch and myself prefer to use a class (in fact two, PMapWriter and PMapReader). 

To conclude:

1. I will review first the work of @gonzaponte which includes already a rewrite (an improvement, as it is) of function s12df_to_s12l.

2. @jmbenlloch and yours truly volunteer to write the PMPas readers and writers... as classes.  It is probably easier to actually come up with the classes than to enter a lengthy discussion about classes versus functions.

**Comment by jjgomezcadenas** [comment]
Sorry, I realise I was not being precise enough. In fact @gonzaponte has not made a PR, but his branch issue149 contains important work that needs to be implemented to the main flow.

**Comment by jacg** [comment]
> My first reaction when I read "a rewrite of a function" (in particular if I wrote the function with some pain) is: why?

Your question is reminiscent of the questions ART developers are asking themselves about IC. Need I remind you that the argument "I suffered while making this, therefore we must keep it and suffer even more" is not one that you yourself find very convincing? I believe that if you *look* at the functions, the original and the proposed replacement, the answer will become clear:

+ The body of `xxx` is 4 lines long; the function it replaces is split into two functions one in pure Python, one in Cython, clocking in at around 49 lines.
+ `xxx` achieves this miracle by using the technique of *not re-inventing the wheel*. I believe some guy gave a presentation on this topic in Valencia, not long ago.
+ `xxx` is understandable by anyone in a few seconds becasue it is expressed at a high level; the original ... erm ... how shall I put this politely? ... is ... not.

The jury (i.e. @neuslopez who is going to do some timings) is still out on the relative performance of the two approaches, but let me make this observation: The core of `xxx` is optimized in Cython by the author of Pandas; the core of `s12df_to_s12l`is optimized in Cython by the author of `invisible_cities/reco/cdf_to_dict`. The former is in a package that has been widely used in data-oriented computing in many fields over a number of years; the latter has been tucked away in a corner of some HEP experiment's software for a couple of months, and is known to contain at least three bugs at last count.

I recommend that you look at `xxx` *first*, because I have a suspicion that by pursuing the ideas expressed in `xxx` we can kill #146, #149 and #158 with one stone, quickly and painlessly.

The fact that there are currently 3 issues open relating to `s12df_to_s12l` does suggest that it contains quite a bit of technical debt.

**Comment by jacg** [comment]
> @jmbenlloch and yours truly volunteer to write the PMPas readers and writers... as classes. It is probably easier to actually come up with the classes than to enter a lengthy discussion about classes versus functions.

I'll use this space to record a prediction I am going to make about the future. My prediction is this:

When all is said and done, we will end up with four functions.

I make no prediction about how long it will take us to get there, and how circuitous a route we will take, but I do predict that we will end up with four plain functions. Or maybe two function factories. Or maybe two curiously parametrized functions. But those are details: to a first-order approximation, we will end up with four functions and no classes. That is my prediction.

In the meantime, have fun programming!

**Comment by neuslopez** [comment]
Timing tests give that "s12df_to_s12l" is about two orders of magnitude faster than 'xxx' see:

-----> %timeit pf.s12df_to_s12l(S1df,10000)
                        10 loops, best of 3: 54.6 ms per loop
------>%timeit pf.xxx(S1df,10000)
                         1 loop, best of 3: 8.26 s per loop

The test I made is over a Kr file. Find a short notebook reading the data in: (https://github.com/neuslopez/ICARO/blob/Timeit_dataframe-to-dict-s12/Timeit_dataframe-to-dict-s12.ipynb).

One thing to notice is that xxx is currently giving "everything" (event,evtDaq,peak, time, ene)...

**Comment by jjgomezcadenas** [comment]
This thread has branched into a discussion related with #146 #149 etc. Since this issues are resolved, I am closing this threat and reopening with a new name, just to start a new discussion from scratch
