### ISSUE TITLE
Blob energies returned as set in paolina.py function blob_energies

### ISSUE THREAD

**Issue by jerenner** [next-exp/IC#238]
Since the blob energies are returned as a set, if they have the same value, the set will contain only 1 element with that value.  Therefore if the user attempts to obtain the energies expecting 2:

```
eblobs = blob_energies(trks[itmax],blob_radius)
iter_eblobs = iter(eblobs)
Eblob1, Eblob2 = next(iter_eblobs), next(iter_eblobs)
```

a `StopIteration` error will occur.  One could get around this by checking the length of the returned set `eblobs` but Paola disagrees because the user should always expect two blobs.  Note that the blob energies being the same value is not necessarily an error - it may happen if the extremes are found close by and therefore include the same energy or of course if the exact energy by chance is found in both extremes.

**Comment by jerenner** [comment]
One possible alternative to be discussed can be found here: 
[https://github.com/jerenner/IC-1/blob/paolinarev/invisible_cities/cities/paolina.py](https://github.com/jerenner/IC-1/blob/paolinarev/invisible_cities/cities/paolina.py)
[https://github.com/jerenner/IC-1/blob/paolinarev/invisible_cities/cities/paolina_test.py](https://github.com/jerenner/IC-1/blob/paolinarev/invisible_cities/cities/paolina_test.py)

**Comment by jacg** [comment]
The probability of two blobs having the same energy is essentially zero. This isn't the problem you seem to be addressing. (If this were the problem, the solution would probably be to return an ordered tuple, rather than a set of blobs. This is simple to implement and offers guarantees that can be used in the tests (and elsewhere)).

The problem you seem to be addressing is that of only having one voxel, which has the consequence of producing the same blob twice, and therefore leads to identical energies in both blobs.

As there is only one blob, the more correct solution would seem to be to return one energy value and one `None`. @jjgomezcadenas agrees with this last point.

**Comment by paolafer** [comment]
I don't agree. There is also the possibility that the track has more than one voxel, but it is short, so each blob includes all the voxels of the track. In this case, you have two well-defined and different extremes and two blobs that have the same energy.
