### ISSUE TITLE
nmax option not stopping execution right away in Dorothea

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#308]
When using a value of nmax inferior to the number of events, the program keeps looping over files. This happens *at least* in Dorothea, but I think it is something common to all cities.

**Comment by gonzaponte** [comment]
I need the input from the master here. I don't feel comfortable calling the method `max_events_reached` in `file_loop` as a means of deciding to stop the loop because it would print a message for a second time.

What do you feel is the best option?:

1. `event_loop` to return a `forced_stop` flag that is used by `file_loop` to decide whether to stop or to carry on with the loop.

2. Use a flag in the same way, but make it a class member.

3. Rearrange the code in `max_events_reached` so it only prints the message once and use the method again in `file_loop`.

4. Other

**Comment by abotas** [comment]
This also happens in irene - i think ya probably everywhere

**Comment by jacg** [comment]
It worries me that every time a city implements an `event_loop` method, this whole bunch of cruft has to be recoded from scratch, in an ad-hoc way.

+ There is very little code reuse.
+ This gives plenty of scope for the implementor to get it wrong.
+ Each new incarnation would need to be tested separately, and for some cities this will give rise to some very slow tests.

(And the counter class that was introduced with its heavy syntax, frankly, makes this even uglier and more painful still. But that's a minor point, for now.)

We need to identify the pattern and see how we can abstract it.

Is there any good reason why `event_loop` in diomira, penthesilea, dorothea (and maybe others) performs the `max_events_reached` check and increments the counter *before* processing the event, 
while in irene, isidora (and maybe others) this is done *after* processing the event?

I suspect it's just an erroneous inconsistency introduced by requiring the implementor to recode this boilerplate *yet again*.

**Comment by jjgomezcadenas** [comment]
The code in the cities has not quite been implemented ad-hoc. It has been written and rewritten many times, and in fact a lot of cruft has been taking away since early versions. A lot has already been abstracted (e.g, file loop).

What remains (event_loop) is what makes one city different from the others. *Almost*. Let me explain.

These are the cities in IC at this moment. 

*DIOMIRA* which transforms MCRD (Monte Carlo Raw Data) in RWF (Raw Waveforms).

*IRENE* which transforms RWF in PMAPS.

*DIOMIRA/PENTHESILEA* which transform PMAPS into KDST (DOROTHEA) or HITS (PENTHESILEA).

ISIDORA, which is a fossil. Please, bear with me and ignore ISIDORA for the moment (we will get rid of her at some point, just not yet now).

So:

I think there is very little overlap between DIOMIRA/IRENE/PENTHESILEA because they do different things (e.g, they transform different sets of data). Certainly one could go into more abstraction (more on that later), but to first order, the transformations they do are different. 

There is A LOT of overlap between DOROTHEA and PENTHESILEA. The reason is that their input is the same (the output is different). So one could reuse quiet a bit of code there.

More generically (and this is partly reflected in the structure of the cities already). DIOMIRA is a MonteCarlo city, IRENE is a PmapCity, Dorothea is a KrCity and Penthesilea is a HitCity. The base class of the city is telling you what they produce (MC RWF, PMAPS, KrDST, HITS). But it turns out that HitCity is derived from KrCity which in turn is derived from PCity. A PCity is a city that reads PMAPS. Both DOROTHEA and PENTHESILEA read PMAPS.

Part of this common functionality has already been abstracted away (e.g, in the file loop). But if one looks at the event loop of PENTHESILEA and DOROTHEA is clear that there is still a lot of common stuff (that comes from the fact that we read the same data and in fact use basically the same filters). 

I think it is relatively easy to use those facts (common data) to simplify and unify the event_loop of both cities (and of any future city reading PMAPS). 

One could go further and imagine cities as simple algorithms that read some abstract flow of data, apply some abstract filters, and write into some stream of data. On this grounds one could possibly unify all of them. I would not do that tomorrow. We don't have so many cities, and I think DIOMIRA and IRENE a close to stable (and different enough between themselves and also different from the cities that read PMAPS). But I propose (and volunteer for the job) to improve Doris and Patty (oh yes, this is how I call them when we are alone the three of us, please do not ask for more details). 

The reason why the max_event_reached is on top of the loop for IRENE and on the bottom for Doris and Patty is related with the fact that Irene does not filter data (so the position of the condition at the top or the bootoom of the loop is irrelevant) while Doris and Patty do (so they implement the condition at the bottom, since we intend max_event_reached on processed events, not read events). One could move the condition to the bottom of the loop in IRENE, but I don't think there is any inconsistency there. 

As for the counter class, the idea was to have a generic counter  and that was the best I could come up with. I am sure that the master can come with much prettier implementations, but old dog does not learn new tricks... (or it takes it a long wile).

**Comment by jacg** [comment]
> The code in the cities has not quite been implemented ad-hoc.

No, but I am specifically referring to the need to repeat, in its full, ugly, tedious and error-prone glory, the logic of skipping events, in every single implementation of `event_loop`. This is being done ad-hoc even though it's almost identical for all cities. This is **bad**.

The fact that event skipping has been completely broken until now, is largely a consequence of this ad-hoc rewriting of the idea. The other main reason for it being broken, is that there are no tests checking that it works!

The important point here, is that we need a way of abstracting event skipping, so that it can be written once, tested thoroughly, and re-used in all the `event_loop` methods (which I completely agree, need to be written ad-hoc for every city, as that is what makes the cities different).

The problem is that it's a flow-control issue, and without syntactic (Lisp-like) macros it is difficult to make abstractions for these.

The discussion of to what extent and how we can abstract other things, and unify the various cities, while interesting and important in general, is completely irrelevant to this particular issue. (And I still suspect that streams could be a very good fit, for that.)

This issue is about the long-term brokenness of event skipping, and the long-term solution is to find a decent abstraction for it, and to stop re-writing it by hand in every city.
