### ISSUE TITLE
Travis taking too long

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#357]
Lately, Travis is taking too long to make the build. The last one is over 20 minutes and seems to be stuck in the tests rather than in the downloads or in the setup. I don't know if the parallel testing is the issue here, but I don't see any other reason. Also, the output of Travis contains stuff I haven't seen before, but I did never pay too much attention to it anyway.

**Comment by jacg** [comment]
This seems to be caused by a new version of hypothesis: lots of tests are now hitting the default timeout limit of 60s. We don't see this in our local repos, because

1. Most of us are running older versions of hypothesis, locally
2. Travis runs the `hard` profile, which tries 1000 cases, while our `dev` profile, which we use by default locally, tries only 10 cases.

I have run the tests on 8 processors with both the `hard` and `dev` profiles on my machine in different versions of hypothesis:

[edit: Added `hard_nocov` column this uses the `hand` profile with `use_coverage = False`. `use_coverage` was not available in hypothesis 3.28]

| Hypothesis version | `dev` run time | `hard` run time | `hard_nocov` |
|--------------------------|----------------:|-----------------:|-----:|
| 3.28.0             | 31s | 100s |
| 3.29.0             | 34s | 250s | 84s |
| 3.30.0             | 33s | 250s | 76s |
| 3.31.0             | 39s | 600s | 83s |
| 3.31.2 (ours at time of writing)   | 38s | 550s | 85s |
| 3.31.4 (latest at time of writing) | 37s | 500s | 71s |
| 3.32.0 (added in an edit)           | 33s | 170s | 76s |

So the sort-term solution would be to specify `hypothesis=3.28` in `manage.sh`. In the long-term we need do understand why these times went up so drastically. [edit: hypothesis `3.32` has been released, and much of the performance problem disappears!]

Incidentally, we are installing hypothesis with `pip` but it seems to be available in `conda` now.

**Comment by jjgomezcadenas** [comment]
Is this connected with the (more or less solved) issue of upgrading hypothesis?

**Comment by jacg** [comment]
I think that this had to stay open, as long as the solution was the **temporary** workaround of **holding back** the version of hypothesis.

Now that we are solving it by using the **most recent** hypothesis, we can probably assume that the problem was caused by hypothesis rather than by us.

If that is the case, the solution can be considered **permanent**, and the issue can be closed.
