### ISSUE TITLE
Dev database during installation

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#367]
We are currently downloading the dev version of the database in our travis build:
```
bash manage.sh download_test_db_dev
```
Is there any reason for that? I have a PR not passing the tests because this db is not up to date.

**Comment by jacg** [comment]
Travis uses `run_tests_par` which calls `download_test_db` if `localdb.sqlite3` is not found. So the separate step you mention does seem superfluous.

I am not really up to speed on the difference between the dev and non-dev versions of the database.

As @jmbenlloch committed that line with the title 'Use dev version of the DB in travis', perhaps he's in the best position to answer your question.

**Comment by jmbenlloch** [comment]
When that commit was made we had a problem with some data from the database. It seemed that some channels which were not masked needed to be masked, so we created a new `dev` DB to do this change.

The idea was to keep two copies of the DB: `production` and `dev`. The new changes will be tested first in the `dev` version and then, if everything was ok, the will be propagated to the production one. But as time has shown, this is difficult to do because is not trivial to keep both syncronized.

Therefore, I think we should revert this change and put `bash manage.sh download_test_db` in travis. If we need to use the `dev` database at some point, we can then copy NEWDB into NEWDB_dev, make the needed changes and try the code, if everything goes well, this changes goes back to the production DB and travis will always test the production one. Opinions?

**Comment by jacg** [comment]
> I think we should revert this change and put `bash manage.sh download_test_db` in travis.

Just remove the line. No need to do it explicitly as the `run_tests*` functions download the production database if no database is found.

**Comment by jmbenlloch** [comment]
> Just remove the line. No need to do it explicitly as the run_tests* functions download the production database if no database is found.

Done. If we agree to do that, there is a PR open with that solution (#368) that could be merged.
