### ISSUE TITLE
Documentation for git(hub)-related stuff

### ISSUE THREAD

**Issue by gonzaponte** [next-exp/IC#411]
What do you (ic-ists) think about making a document in the repo on how to proceed with reviews and merging PRs?

New users will welcome this help and it can be updated with a proper PR submission and discussion rather than commenting on a (closed) old issue. We can use it to:

- describe how to make a good commit history
- describe how a review should be performed (in terms of tests, readability, the previous point, etc.)
- describe how to merge PRs (single-commit and multiple-commit)

**Comment by jacg** [comment]
I think that this is important, but perhaps not at the top of the priority list, as all the things you mention are done by more experienced members of the team, who have been given write-permission for the repo. By their very nature, these are things which are done by a self-selecting group of individuals who are more familiar with the way things are done in IC than the average developer.

I think that providing documentation for the true beginner should have a higher priority.

But yes, this also needs to be documented.

**Comment by Aretno** [comment]
I have to say that I'm suposed to do a small change in Penthesilea and I really have no idea of the correct way of doing everything that has been listed by @gonzaponte. I had the tutorial long ago but since I have not put it into practice it's like I didn't have it at all. Still, I understand this not being a priority so I'll probably bug @gonzaponte in the meantime.

**Comment by jacg** [comment]
I think that at this stage the best thing to do is to get someone who is *geograhpically colocated* to help you go through it.

If, in the process, you could make notes of what it is that needed explaining, then those could form the basis of the documentation that we need to write here.

**Comment by Aretno** [comment]
In the end I got help from @jmbenlloch but it was a quick fast remembering of the tutorial (seems that I kind of remembered some things in the end) so we weren't sure on how to do those notes. 

In summary he explained to me how a PR should be done, how should I make branches and push them to my fork and not nextic, a bit about resetting, rebasing, etc. and how to add the commit description. We did not talk much about the tests, merging with single/multiple commits or about the review in detail.

**Comment by jacg** [comment]
No problem. If it went smoothly and quickly then don't worry about the notes.

**Comment by jacg** [comment]
I suspect that @carmenromo and any other newly-appointed mergers would be very well positioned to drive this: because they will shortly be learning the process by putting into practice repeatedly, they can make notes on what difficulties newcomers have to overcome ... the sort of stuff that the experts take for granded and don't even realize might need mentioning.

Having seen @carmenromo's note-making ability, I think this could work out very well indeed.

**Comment by carmenromo** [comment]
But I don't understand what should I focus the document. How to do a PR and merging it? Which kind of document?

**Comment by jacg** [comment]
Being an active participant in IC requires the use of Git and GitHub. Anything that helps people get used to these tools and some of the specific ways in which we use them in IC, could be useful.

In your current specific case, you are in the process of becoming an IC PR merging expert, from a recent starting point of almost complete ignorance on the subject. Imagine that you didn't have the opportunity to communicate with other team members on this subject. What is the ideal document that would have taught you to do the merge? Write it.

@gonzaponte mentions other points, which you might like to think about in the background, but I would concentrate on merging PRs, because you are currently living through the process of learing how to do it, so you have a very important perspective on it.

> Which kind of document?

Do you mean, what format? If so, we had decided to use Sphinx (which uses RST) for our documentation.
