### ISSUE TITLE
load_pmaps very slow

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#485]
Apologies if this is a known issue or I'm using the wrong interface but...

I've been reading a few pmaps both from data and MC for a couple of projects aimed at understanding our sipm noise simulations. I've noticed that the load_pmaps function is extremely slow.

using load_pmaps_as_df I can load the whole (granted very large) MC pmaps file in a few seconds and get on with the checks I want to do, when I tried to use load_pmaps I was still waiting for it to read the file after 15 minutes and gave up and killed the process.

I understand that load_pmaps puts things into a format which is a bit more flexible and object orientated maybe but the time difference still seems huge.

**Comment by jmbenlloch** [comment]
I have also encountered that issue running MC files with 10k events for RESET.

The problem I think is that `load_pmaps` reads the whole tables as a dataframe and then goes event by event filtering using pandas. This is ok for small files (few undreds of events, like the situation in Canfranc), but it is a lot of work for many events (there are many rows in the tables).

An alternative would be to read event by event from the HDF5 file using the filtering capabilities of pytables (and also taking advantage of the index we have created in the pmap file). Therefore, you read from disk only the part relevant for a given event and then pandas won't have a lot of work to do.

You can find a function implementing that scheme here: https://github.com/jmbenlloch/IC-1/commit/c91a748e083160a2de028991b19ae011e63431d2

This approach is faster for big files (I don't remember the numbers, maybe gos from 20 minutes with `load_pmaps` to 4-5 minutes with this new function). For smaller files the new approach is slower due to caching from disk, etc. If you read event by event you have more IO, but you decrease a lot the search time.

You can try the function if you want.

**Comment by andLaing** [comment]
I've been able to speed things up using the load_pmaps_as_df function which is called by the other function at the start to load the dataframe. It takes a few seconds. The problem for me seems to be in the part where the function creates pmap objects but as you say, it might be even faster to read the pytables directly

**Comment by jacg** [comment]
> I understand that `load_pmaps` puts things into a format which is a bit more flexible and object orientated maybe but the time difference still seems huge.

Very important point: the PMAPs interface is just that; an interface. It says nothing about the implementation. If the implementation behind the interface is too slow, we should be able to improve that without changing the interface or any of the client code ... if we got the inderface design correct. That's the whole point of decoupling interface from implementation.

Specifically, if the problem is related to having to unreasonable times to load huge data sets before being able to do anything with them, then this should be solvable by putting some kind of lazy implementation behind the interface. Whether or not this can be done not only in theory but also in practice, crucially depends on us having designed a good enough interface! I'm sorry, I've been out of the picture for so long, that I forget the details of the interface, and I don't think I ever saw the implementation behind it, so I can't be more specifc at present.

**Comment by andLaing** [comment]
Related to this issue (a bit) and to a comment by @jacg about using the correct exceptions (sorry I can't find where it was to link). I got an odd warning from base_cities.get_pmaps_dicts (basically just a wrapper around load_pmaps) when running penthisilea: "Empty file. Skipping." , on a file I knew to have data.

If I run the code on its own I get an error from np.reshape as the source of the error. The problem stems from something unrelated but a more direct warning might be useful.

**Comment by jacg** [comment]
Was the warning a print to stdout, or a real warning?

Would it be possible to write an automated test that points out the problem? (Obviously difficult, if it's just a print ... which is why we should use real warnings, rather than just printing stuff to stdout.)

**Comment by andLaing** [comment]
Maybe this issue can be closed given @mmkekic improved the function in #524 ?

**Comment by gonzaponte** [comment]
> Was the warning a print to stdout, or a real warning?

The "Empty file. Skipping" message is a print to stdout. It was originally intended to skip corrupt files but seems that it can be produced in other cases. Anyway, this is orthogonal to this issue, so I am closing it and open a new one.
