### ISSUE TITLE
Even less information than before

### ISSUE THREAD

**Issue by andLaing** [next-exp/IC#518]
The new README gives even less information than it did before.

For example, there is now no information about how to update the database, is it not necessary anymore?

Also, are extra environment variables necessary? I now can't do source deactivate. I was warned about this one but the alternative I was told, just 'deactivate' doesn't work either:

> -bash: deactivate: command not found

Moreover, work_in_python_version 3.6 tries to reinstall every time and gives errors rather than detecting and skipping over the install part.

**Comment by carmenromo** [comment]
The same happens to me with work_in_python_version 3.6

**Comment by jacg** [comment]
The trouble is, this lies beyond the reach of our automatic test suite.

I think that if you trash any pre-existing conda installations you might have, and it should work sensibly. (In order to test this, I would have to keep trashing my new conda installation, and keep replacing it with one deliberately installed using the old style, which would just be too much work.)

Please remove any old conda installation you have. This requires 2 steps (off the top of my head)

1. Remove your `miniconda` directory (to do it reversibly, just rename it, maybe to something like `miniconda.bak`).
1. Remove the line from your shell config file that puts conda in `PATH`.

With old conda out of the way

1. Open a new shell
1. `cd` into the IC top directory
1. run `work_in_python_version`

If *that* doesn't work, then there's a serious problem; let me know. But, sorry, making this robust in the face of old-style conda installations (which I recommended everyone replace months ago) is just too costly, at present.

Oh, as for 

> For example, there is now no information about how to update the database, is it not necessary anymore?

I refuse to waste resources on patching this with a crappy, ad-hoc, temporary, unreliable solution. This requires Git LFS (#210), to do it easily and properly once and for all ... and that's going to be ready any minute now, right @jjgomezcadenas ?

Once that happens, you will always magically have the correct version of the database ... for all commits that do not precede the feature being enabled. So, yes, it is about to become 'not necessary any more' therefore I cannot justify spending time on documenting it.

**Comment by jjgomezcadenas** [comment]
Furthemore: you should have in your bash_profile something like:

     source /Users/jjgomezcadenas/miniconda/etc/profile.d/conda.sh

and you should no longer add manually conda to your pythonpath

If everything in your setup is correct and you type 

     conda --version

You should get the answer:

     conda 4.5.4

This means that you can now run manage.sh and things should work. The system tries to re-insall conda if no conda commands are available, which in turn implies that the source of conda.sh did not go well.

Everything works in my system, so it should not be hard to make it work in yours.

**Comment by andLaing** [comment]
Hi

Looking through the errors and advice conda was trying to give me I got a bit further. You need to send a couple of commands too the .bashrc/.bash_profile:
`echo ". /path/to/miniconda/etc/profile.d/conda.sh" >> ~/.bash_profile`

and

` echo "conda activate" >> ~/.bash_profile`

This gets past any problems meaning that things don't work but I still don't have a `deactivate` command that works. Minor point maybe.

The two quoted bits above should maybe be added to the README though

**Comment by jacg** [comment]
> I now can't do source deactivate. I was warned about this one but the alternative I was told, just 'deactivate' doesn't work either:

The modern style is `conda deactivate`. Does that work for you?

> Looking through the errors and advice conda was trying to give me I got a bit further. You need to send a couple of commands too the .bashrc/.bash_profile:
>
>  `echo ". /path/to/miniconda/etc/profile.d/conda.sh" >> ~/.bash_profile`

I recall writing this advice in a number of places. I apologize if none of them continue to exist in a README easily accessible to you. It definitely should be there.

> and
>
> `echo "conda activate" >> ~/.bash_profile`

I recommend against this one. It shadows your system Python, and indiscriminently doing this in every shell will sooner or later screw up something that relies on it. Just activate a conda env if and when you need one. The ability to use conda only when you need it is one of the advantages of the new style.

**Comment by jacg** [comment]
Apologies, last comment was inadventently sent before it was ready. Please see the edit.

**Comment by jmbenlloch** [comment]
> This requires Git LFS (#210), to do it easily and properly once and for all ... and that's going to be ready any minute now, right @jjgomezcadenas ?

I don't think it is a good idea to implement LFS *right now*. LFS is a backward incompatible change, all clients must change their setup, issues will arise for sure (for instance, we have not tested it on Mac OS). In August nobody will be at IFIC (starting with me), so everything would much more complicated than needed. 

It would be a lot easier to do in September when everybody is back from vacations and we can check everything works with almost everybody at the same time with *peras*. In other case, I think is very likely that some people are not going to be able to work (as @paolafer in #519).

**Comment by gonzaponte** [comment]
Can we close this issue @andLaing @jmbenlloch?

**Comment by andLaing** [comment]
I think things have been updated in all the things I was complaining about at the time.

Fine to close for me.
