### ISSUE TITLE
test_mean_for_pmts_fee_is_unbiased  fails in python 3.6

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#521]
@andLaing this test fails in python 3.6. It does not fail in python 3.7. Any idea of what's going on?

______________________ test_mean_for_pmts_fee_is_unbiased ______________________

square_pmt_and_sipm_waveforms = (5000, 5, array([[5000, 5000, 4995, ..., 5038, 5014, 4985],
       [5000, 5000, 5003, ..., 5015, 5041, 5064],
       [...4937, 4962],
       [5000, 5000, 4996, ..., 4984, 4982, 4971],
       [5000, 5000, 5005, ..., 4997, 4989, 4990]]), ...)

    @flaky(max_runs=3)
    def test_mean_for_pmts_fee_is_unbiased(square_pmt_and_sipm_waveforms):
        _, _, pmts_fee, _, _, _, _ = square_pmt_and_sipm_waveforms
        pmts_bls = csf.subtract_mean(pmts_fee) # ped subtracted near zero
        sums     = np.sum(pmts_bls, axis=1)    # cancel fluctuations very close to zeo
>       assert np.allclose(sums, 0)
E       assert False
E        +  where False = <function allclose at 0x10d09d400>(array([-5.00875555e+03, -5.00862713e+03, -2.09547579e-09, -5.82076609e-10,\n       -4.13274392e-09]), 0)
E        +    where <function allclose at 0x10d09d400> = np.allclose

invisible_cities/reco/calib_sensors_functions_test.py:252: AssertionError
===Flaky Test Report===

**Comment by jacg** [comment]
@jjgomezcadenas Is the behaviour consistent? I see this test is already marked flaky, but I get the impression we have a number of increasingly flaky tests in our collection, especially some of the hypothesis based ones?

For the hypothesis-based ones, the hypothesis database will ensure that your machine immediately uses any counterexamples that you have found in the past: so, once it has failed on your machine, it should continue to fail until you fix it; but on Travis, where there is no database, because everything is installed from scratch on every build, it's hit and miss.

**Comment by jjgomezcadenas** [comment]
Turns out that the problem seems to have been related with updating of the data base. With the last update things work well in python 3.6 and python 3.7
