### ISSUE TITLE
Problem with the last version of the data base

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#522]
I have downloaded the latest version of the data base and a zillion tests fail. Reverting back to the previous version of the data base, all test pass. This shows that **there is a serious problem with the last version of the data base**. @msorel, @andLaing, @jmbenlloch who has uploaded the last version of the DB?

**Comment by andLaing** [comment]
I haven't updated anything lately in the mysql.

I did a database update in IC earlier today though and got no errors.

**Comment by jjgomezcadenas** [comment]
No need to panic. I downloaded the "dev" version of the data base (that surely produces those errors, a different question is whether we need that "dev" version in IC).

**Comment by msorel** [comment]
this is to be confirmed by @jmbenlloch but we probably can:
1. eliminate the download_test_db_dev function in manage.sh
2. delete or empty the NEWDB_dev MySQL database itself,
to avoid confusion like this one

Details:
The NEWDB_dev MySQL database, which is what 'bash  manage.sh download_test_db_dev' gets a local copy of, was there for testing purposes ages ago, once IC first switched to using a DB

Soon after that we started using the standard MySQL DB for NEW also in IC, simply called NEWDB. This was done once tests were successful and relevant tables were merged from NEWDB_dev into NEWDB, by jose maria. NEWDB is what gets downloaded with 'bash   manage.sh download_test_db'.  At least the relevant tables of it (there is a lot of unnecessary crap in NEWDB right now, but thats another story)

NEWDB is what we have been updating since, and I am not aware of any need for NEWDB_dev 

again, jose maria should confirm before actions taken
