### ISSUE TITLE
Analysis DST contents

### ISSUE THREAD

**Issue by msorel** [next-exp/IC#556]
First, many thanks to @jacg , @jjgomezcadenas , @gonzaponte , @jmbenlloch  and all others involved to move to liquid cities! Is it now time already to start discussing new cities and functionalities?

I am particularly interested in a new city that provides an analysis DST (adst) with event-based information (one row per selected event) for analysis. @jjgomezcadenas proposed the name esperalda for this city, i believe, and adst for the output nutple. This city is highly recommended as basis for december results. 

We can start from scripts from @paolafer and alberto and make a city out of it. This city should run after energy corrections are applied hit-by-hit, and after paolina for track/blob reconstruction is also run.

we can start by discussing adst contents. 

I think this adst should include quantities for event selection, such as:
- corrected event energy information for calorimetric event selection 
- zmin, zmax, rmax information for fiducial event selection
- s1 and s2 multiplicities
- s1 information (particularly s1 charge) for alpha veto and other selections
- paolina track and blob information (ntracks, eblob1 for highest energy track, eblob2 for highest energy track, ...) for topological event selection

Other quantities should also be included beyond event selection:
- xavg, yavg, zavg for charge-weighted average of event position 
- MC truth information (Z and A for decaying isotope, detector volume of decay)  to be filled for MC events only 

I am sure I am forgetting many quantities here, and many of you will have other suggestions. Please paste them here. Since it will only be one row per event, I am fine with adding many columns, here. File size will be small.

Thanks!

**Comment by jjgomezcadenas** [comment]
We have been discussing about this city also with @jerenner and @mmkekic. Here is my understanding on how we should proceed.

- Currently DOROTHEA generates a kdst (global variables, useful for Krypton analysis) and PENTHESILEA generate a hdst (uncorrected hits and no global variables). My point of view is that we could proceed forward merging both of them, but @gonzaponte (and others) seem to prefer to modify PENTHESILEA so that the hdst includes also global variables (S1, S2, etc), in different "banks". This implies reprocessing all the hdsts, but if we are OK with paying this price, adding such an info is trivial with the new cities (just a few more sinks). SO WE NEED TO DECIDE ON THAT.

-- The DNN-based analysis requires voxels, rather than hits. Also the classical analysis (Paolina-based) requires voxels. So, one possibility is that we writ a city that reads the hdst, corrects the hits, voxelizes them and writes a vdst (voxel-dst) which stores global variables (S1, S2 and such) plus voxels, rather than hits. This step is justified by the fact that computing hits (PENTHESILEA) is time-consuming, but correcting hits and voxelizing is a fast process. Thus, starting from hdsts we can make fast reprocessing to produce vdsts when needed (e.g., improvements in hit corrections). Also, we can make dedicated vdsts for classical analysis (large voxels) and DNN analysis (smaller voxels and probably need to test different voxel size). So, this city, which I would like to call ESMERALDA, should be the next step.

--Then we can write another city that reads voxels, calls Paolina, computes overall variables of interest and produces the adst. Let me call it ANASTASIA.

If we agree on the procedure (to be discussed also with @jahernando, then:

1.- @gonzaponte should add gloabl variables to PENTHESILEA, after every one agrees what we add (in first approximation I would add everything that is in the kdst). Then we need to reprocess all relevant hdst data (low background data and the recent source data at least).

2.- @jerenner and @mmkekic under @gonzaponte supervision write and test ESMERALDA. We then need a production (in fact possibly several productions) of vhits.

3.- @paolafer, @msorel  and Alberto write ANASTASIA, after everybody agrees what goes into the adst, and we proceed with productions.

4.- We need a production group. I propose that @carmenromo, @mmkekic, and Alberto share production work (with supervision from @jmbenlloch, @paolafer, @gonzaponte). 

This issue is good stuff for discussion in the next software organization meeting.

**Comment by msorel** [comment]
@jjgomezcadenas this is fine with me. separating esmeralda and anastasia into two separate cities (one for voxelization, one for paolina tracking) brings extra modularity (which i am always fine with). plus, it ensures that classical and dnn-based topological analyses share common formats and productions one step further down the line, up to vdsts. it will be easier to compare the two analyses

reprocessing low-background and recent calibration data with extended hdst info should not be a big problem, it is a fast processing step

as far as how to pass through global (event-based) variables from one city to another: OK with me to extend penthesilea and start from that, if this is the preferred choice. 

in addition to kdst info, does this mean that also MC truth (that we also need for MC productions, and currently living in separate hdf5 groups) also needs to be copied into the hdst structure, like kdst info?

@gonzaponte , @jerenner , @mmkekic and @jahernando at least should also comment before making pull requests to extend penthesilea and/or start off with esmeralda, anastasia

if this scheme is to be used for december results, all the software changes should be merged by the end of october, so that we have november and first week of december for productions and data analysis

**Comment by paolafer** [comment]
Hi all! 
Regarding MC truth, I would keep it like it is right now, since it contains all the information we have, and in my experience it is useful to have it at hand, when you're studying and optimizing reconstruction, without a previous selection. Therefore, I would maintain the structure that comes from nexus (this structure can maybe be improved, but this is another issue).
As for adst, I would keep track-based rows, instead of event-based. Usually there are just a few tracks per event, so it doesn't add a lot of information and it is mandatory if we want to try merging algorithms, for instance. For the same reason, we need to save also voxel information, as a different table, maybe.

**Comment by jjgomezcadenas** [comment]
@paolafer does that mean that you would like to add MC truth info to all DSTs after hdst?

As for global versus local dsts. ESMERALDA will provide voxels. You claim (and I actually agree) that we need voxels (plus tracks) in addition of global variables for meaningul analysis. If this is the case, then we don't need a vdst and an adst, we could do with a single city that writes a dst which includes everything needed. MC info, global variables, voxels and tracks. Acutally this may be the more reasonalbe way to go to avoid excesive processing and atomization of files.

This needs to be agreed, though.

**Comment by paolafer** [comment]
> does that mean that you would like to add MC truth info to all DSTs after hdst?

Yes, in the same way we're doing now with the output of the previous cities (diomira, irene and penthesilea): they all use the MC info writer, which replicates the data structure coming from nexus.

I don't have a strong opinion for a unique city or two. Right now, Alberto (who needs a github account, if he doesn't have one...) and myself are saving tracks and voxels into two different tables, in the same file, in order not to replicate track-level information for every voxel. We could maybe implement something along this line for the city.

**Comment by jjgomezcadenas** [comment]
The debate is not one city or two, but the structure of the dst after PENTHESILEA. If we opt for a more complete dst (including voxels, tracks and global info) then we only need one city and we only produce one extra data transformation.

**Comment by paolafer** [comment]
Ok, I got confused by reading

> If this is the case, then we don't need a vdst and an adst, we could do with a single city that writes a dst (...)

**Comment by mmkekic** [comment]
Whats the status of this topic? Shell we arrange a meeting to make a plan and divide the work?

**Comment by jjgomezcadenas** [comment]
Yes, first we need a discussion @jahernando, then we divide the work.

**Comment by msorel** [comment]
A planning meeting sounds good to me. Tomorrow (Fri) 10:00am? Monday 10:00am? I am flexible.

**Comment by jjgomezcadenas** [comment]
10 am tomorrow is fine for me. We need to harry up, so that @mmkekic and friends can start working

**Comment by gonzaponte** [comment]
I am available tomorrow at 10 am too.

**Comment by jerenner** [comment]
10am is ok with me

**Comment by mmkekic** [comment]
For me too (via Skype or Zoom)

**Comment by paolafer** [comment]
I have a medical appointment at 08:45, it's unlikely I will manage to be at IFIC by 10, but I could maybe go home and connect via zoom by that time.

**Comment by msorel** [comment]
would 11am tomorrow still work for everybody? looks like it would be better for @paolafer , who should attend

**Comment by jerenner** [comment]
11 AM is ok with me

**Comment by paolafer** [comment]
Fine with me, too.

**Comment by paolafer** [comment]
@ausonandres should also be present.

**Comment by ausonandres** [comment]
11 am is fine for me too.

**Comment by mmkekic** [comment]
11 is fine with me too (though I'd have to leave ~12:15 )

**Comment by jjgomezcadenas** [comment]
Ok for me @jahernando?

Enviado desde mi iPhone

**Comment by jahernando** [comment]
Sí, por mi también!

**Comment by mmkekic** [comment]
Solved with #612
