### ISSUE TITLE
script manage.sh behaves in an unexpected way in Mac OS X

### ISSUE THREAD

**Issue by jjgomezcadenas** [next-exp/IC#71]
source manage.sh c

Unrecognized command: c

Usage:

source -bash install_and_check X.Y
soruce -bash install X.Y
source -bash work_in_python_version X.Y
bash -bash make_environment X.Y
bash -bash run_tests
bash -bash compile_and_test
bash -bash download_test_db
bash -bash clean
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

[Process completed]

**Comment by jjgomezcadenas** [comment]
The error reported is no longer there, I was looking at the wrong fork. But there is still something that does not work completely well in the Mac

IC$ source -bash install_and_check 3.5
-bash: source: -b: invalid option
source: usage: source filename [arguments]

**Comment by jjgomezcadenas** [comment]
Sorry again, wrong paste:
source -bash manage.sh install_and_check 3.5
-bash: source: -b: invalid option
source: usage: source filename [arguments]

**Comment by jjgomezcadenas** [comment]
In other words, it appears that source --bash manage.sh does not work in OS. source manage.sh works

**Comment by jacg** [comment]
Well, yes, the only 2 valid options are

1. `source manage.sh <command> [arg]`
2. `bash    manage.sh <command> [arg]`

The problem is that the usage message suggested nonsense (replacing `manage.sh` with `-bash`), and you believed and copied the nonsense.

I do not have access to OS X here, so please check that the upcoming PR really solves your problem before accepting it.
