### ISSUE TITLE
Beersheba crashes under certain circumstances when detector_db isn't given.

### ISSUE THREAD

**Issue by jwaiton** [next-exp/IC#850]
I'm writing this issue to ask for advice on what the best feasible plan of action should be for an issue I've found within IC, specifically Beersheba (in the `v2-development` branch).

Beersheba's default config file does not require a `detector_db` to be provided, but not doing so is very likely to cause the city to crash. The error itself is rather cryptic, but after some investigation I've come to the conclusion that Beersheba (if not given a detector_db to work from) uses some default geometry db and assigns the X-Y spatial grid to a variable `det_grid`. 

This causes issues when your tracks are outside this default geometry space (I'm assuming the default space is NEW). The code will crash with an error giving very little information to the user.

Here is the error, I believe it's re-creatable if you use NEXT-100 Sophronia data and don't provide a `detector_db` variable, but I'd love for someone to double check.
[error_IC.txt](https://github.com/next-exp/IC/files/14125411/error_IC.txt)

@gonzaponte and I have discussed different ways of addressing this, the most obvious way would be to require `detector_db` as a non-optional argument for Beersheba, and possibly for all cities that should have them included.

For this specific scenario, I also think it would be useful to have a check/catch somewhere for if events are occurring outwith the detector_db space provided.

I'd be happy to do both, and will start producing a PR addressing the `detector_db` argument as soon as possible. I would appreciate any advice on how to go about either of these two fixes (Does IC have a universal 'cities' catch-section that checks for required arguments? Should I only do this for Beersheba & key cities as it may mess with others? etc).

Thanks,
John

**Comment by gonzaponte** [comment]
> Does IC have a universal 'cities' catch-section that checks for required arguments

Yes, and it's already implemented. I would have to check every city, but it seems that Beersheba has already `detector_db` as a required argument. The problem seems to be that we have a sneaky bit of code 
https://github.com/next-exp/IC/blob/94c2f21830e691d21afc767785bd8886c88543d5/invisible_cities/cities/components.py#L109-L111
That provides a default for `detector_db` if not given. I would start by removing those lines and see if something changes.

> Should I only do this for Beersheba & key cities as it may mess with others?

If I'm right about the above, this will have an implication in every city.

**Comment by jwaiton** [comment]
Removing those three lines and trying to run Beersheba without a `detector_db` variable assigned in the config returns the error:
`ValueError: The function 'beersheba' is missing an argument 'detector_db' of type 'str'`.

This is the expected behaviour, and would avoid the issue mentioned in my first comment. Should I check every city to see if this has any sort of adverse behaviour on them?

It doesn't however resolve the issue that if you somehow generate an event outwith your detector geometry, Beersheba will return a nonsense error. I'm not sure if this is a relevant issue, as it's a bit of an edge-case, and I'm assuming previous cities have checks for this sort of thing before Beersheba.

**Comment by gonzaponte** [comment]
> Should I check every city to see if this has any sort of adverse behaviour on them?

Yes, please.

> if you somehow generate an event outwith your detector geometry, Beersheba will return a nonsense error
> I'm assuming previous cities have checks for this sort of thing before Beersheba.

I don't think we have this kind of checks as we have been always working with the same detector. This will require an ad-hoc solution for each city, I am afraid. It would be great if you can take care of that :)

**Comment by jwaiton** [comment]
First thing I've noted is that doing this increases the errors from the tests from:
`1 failed, 1105 passed, 17 skipped, 4 xfailed, 9 warnings in 125.94s (0:02:05)`
To:
`19 failed, 1087 passed, 17 skipped, 4 xfailed, 1 warning in 128.80s (0:02:08)`

All the new errors are from esmeralda, beersheba, isaura and 'writer_test_city' not having the argument `detector_db` provided, so I can see where it's now required and resolve these explicit errors.

There may be more discrete errors, but I'm not sure how to gauge those.

**Comment by gonzaponte** [comment]
> I can see where it's now required and resolve these explicit errors

excellent!

**Comment by jwaiton** [comment]
Simply adding `detector_db = 'new'` to Esmerelda, Isaura, and Beersheba's config files resolves most of the errors. The trickier error appears to be with `writer_test_city`. The remaining errors occur due to the function `compare_signature_to_values` [here](https://github.com/next-exp/IC/blob/94c2f21830e691d21afc767785bd8886c88543d5/invisible_cities/core/configure.py#L157), which makes sure that the signature of the city matches that which is passed through to it.

Because I've removed the lines from the city class that provided the default detector geometry [shown here](https://github.com/next-exp/IC/blob/94c2f21830e691d21afc767785bd8886c88543d5/invisible_cities/cities/components.py#L109-L111), this test imports the city structure from components.py, but cannot find a `detector_db` value to pass-through as it would have previously.

I'm currently trying to think of an elegant solution for this, but haven't come up with anything neat other than providing `writer_test_city` with a default `detector_db` value, which I feel may cause problems (whats the point of the test if you provide it with the value it needs to succeed outwith the input?)

**Comment by jwaiton** [comment]
For example, if I alter [this line](https://github.com/next-exp/IC/blob/v2-development/invisible_cities/io/indexation_test.py#L47) to include `detector_db = 'new'` as an argument, rather than relying on it being passed through from `components.py` as was done previously, the errors disappear. 

Does doing this invalidate the test? As far as I can tell it doesn't, as the purpose of the test is to see if the different writers open the file-type as expected (hits_writer contains the "RECO" group, kr the "DST" group), but I may be misinterpreting what this test does.

**Comment by gonzaponte** [comment]
> The remaining errors occur due to the function compare_signature_to_values [here](https://github.com/next-exp/IC/blob/94c2f21830e691d21afc767785bd8886c88543d5/invisible_cities/core/configure.py#L157),

It would be good if you could open the PR already so we could see your changes more directly and the tests failures directly in CI. (and continue the conversation over there).

> but haven't come up with anything neat other than providing writer_test_city with a default detector_db value

which is perfectly fine. This test *needs* to provide a value with the new implementation. The only reason it was not doing so is because there was a default value (because NEW was the only detector until then). The fact that the test is failing is telling you that the call signature to a city has changed, because that's what you did.

> whats the point of the test if you provide it with the value it needs to succeed outwith the input?

This is the equivalent of having a function `f(x)` with a test `test_f()` that calls `f`. Imagine that later you change `f` to be `f(x, y)`. What's the point of changing `test_f`? Well, `test_f` needs to call `f` with the correct signature, so if you change the signature of `f`, the test must also be updated. You are not necessarily changing *what* you test, you are just updating the test to reflect the new signature of `f`.
In the specific case you are dealing with, `writer_test_city` was receiving `detector_db = "new"` from the `city` decorator. Now, this decorator no longer does that, and `detector_db` must be provided by the caller, so the test must provide the same value that was being provided before in order to maintain its logic.

**Comment by gonzaponte** [comment]
> Does doing this invalidate the test? As far as I can tell it doesn't,

I didn't see this before my previous message. No, it doesn't!

**Comment by jwaiton** [comment]
Sorry for the delay, I've made the pull request now.

**Comment by jwaiton** [comment]
With detector_db now required as an argument [here](https://github.com/next-exp/IC/commit/ec611b4c5f957a528e5f315847374046789fdb14), this issue can be closed I think.

You may still have weird edge cases if events somehow make it to beersheba while being outwith the detector dimensions, but I don't think that should be possible within IC.

**Comment by gonzaponte** [comment]
This should have been closed automatically, but the syntax works only for the master branch.
